name: AUR Package Build & Publish

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build-packages:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - mesa-git
          - lib32-mesa-git
          - lutris-git
          - umu-launcher-git

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create output directory
        run: mkdir -p dist

      - name: Build ${{ matrix.package }}
        run: ./docker-build-package.sh ${{ matrix.package }} dist

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pkg-${{ matrix.package }}
          path: dist/*.pkg.tar.zst
          retention-days: 1

  publish-repo:
    needs: build-packages
    runs-on: ubuntu-latest
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: new_packages
          pattern: pkg-*
          merge-multiple: true

      - name: Checkout Target Repository
        uses: actions/checkout@v4
        with:
          repository: archlinux-gaming-ci/archlinux-gaming-ci.github.io
          token: ${{ secrets.RELEASE_TOKEN }}
          path: repo-dist
          fetch-depth: 0

      - name: Move Packages and Update Database
        run: |
          mv new_packages/*.pkg.tar.zst repo-dist/x86_64/
          docker run --rm -v ${{ github.workspace }}/repo-dist/x86_64:/repo archlinux/archlinux:base-devel /bin/bash -c "cd /repo && repo-add -n -R archlinux-gaming-ci.db.tar.gz *.pkg.tar.zst"

      - name: Commit and Push
        working-directory: repo-dist
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update packages: $(date -u +'%Y-%m-%d %H:%M:%S')"
          git push origin main
